# Generated by Django 5.1.6 on 2025-02-26 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Color",
            new_name="Brands",
        ),
        migrations.RenameModel(
            old_name="Car",
            new_name="Cars",
        ),
        migrations.RenameModel(
            old_name="Brand",
            new_name="Colors",
        ),
    ]
